# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iip_smr_web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title_header', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, help_text='Markdown allowed.')),
            ],
            options={
                'verbose_name_plural': 'Static Pages',
            },
        ),
    ]
