# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iip_smr_web_app', '0002_staticpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title_header', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('short_summary', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True, help_text='Markdown allowed.')),
                ('relevant_inscription_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
