# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iip_smr_web_app', '0004_storypage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='thumbnail_intro',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
