# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iip_smr_web_app', '0005_storypage_thumbnail_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypage',
            name='thumbnail_intro',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
